# Generated by Django 5.1.15 on 2026-06-12 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plataforma', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('LINKEDIN', 'LinkedIn')], max_length=20)),
                ('nome_exibicao', models.CharField(max_length=255)),
                ('external_id', models.CharField(max_length=255)),
                ('access_token', models.TextField(blank=True)),
                ('token_expira_em', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ativa', models.BooleanField(default=True)),
                ('ligada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_sociais_ligadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conta social',
                'verbose_name_plural': 'contas sociais',
                'ordering': ['plataforma', 'nome_exibicao'],
                'unique_together': {('plataforma', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo_interno', models.CharField(max_length=255)),
                ('texto', models.TextField(blank=True)),
                ('link_url', models.URLField(blank=True, max_length=500)),
                ('estado', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('AGENDADO', 'Agendado'), ('A_PUBLICAR', 'A publicar'), ('PUBLICADO', 'Publicado'), ('PARCIAL', 'Parcial'), ('FALHOU', 'Falhou'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20)),
                ('agendado_para', models.DateTimeField(blank=True, null=True)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicacoes_marketing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'publicação',
                'verbose_name_plural': 'publicações',
                'ordering': ['-created_at'],
                'permissions': [('view_publicacao', 'Ver publicações'), ('add_publicacao', 'Criar publicações'), ('change_publicacao', 'Editar publicações'), ('delete_publicacao', 'Eliminar publicações'), ('publicar', 'Publicar e agendar'), ('gerir_contas', 'Ligar contas sociais')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PublicacaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nivel', models.CharField(choices=[('INFO', 'Info'), ('AVISO', 'Aviso'), ('ERRO', 'Erro')], default='INFO', max_length=10)),
                ('mensagem', models.CharField(max_length=500)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='marketing.publicacao')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicacaoMidia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ficheiro', models.FileField(upload_to='marketing/')),
                ('tipo', models.CharField(choices=[('IMAGEM', 'Imagem'), ('VIDEO', 'Vídeo')], default='IMAGEM', max_length=10)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='marketing.publicacao')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PublicacaoDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plataforma', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('LINKEDIN', 'LinkedIn')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('A_PUBLICAR', 'A publicar'), ('PUBLICADO', 'Publicado'), ('FALHOU', 'Falhou'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('external_post_id', models.CharField(blank=True, max_length=255)),
                ('erro', models.TextField(blank=True)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinos', to='marketing.contasocial')),
                ('publicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='marketing.publicacao')),
            ],
            options={
                'ordering': ['plataforma'],
                'unique_together': {('publicacao', 'plataforma', 'conta')},
            },
        ),
    ]
