# Generated by Django 5.1.15 on 2026-06-03 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoModulos',
            fields=[
                ('id', models.CharField(default='default', editable=False, max_length=20, primary_key=True, serialize=False)),
                ('modulo_salas_ativo', models.BooleanField(default=True)),
                ('modulo_viaturas_ativo', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuração de módulos',
                'verbose_name_plural': 'configuração de módulos',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('capacidade', models.PositiveIntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='espacos/salas/')),
                ('descricao', models.TextField()),
                ('localizacao', models.CharField(max_length=255)),
                ('recursos', models.JSONField(blank=True, default=list)),
                ('mobilidade_reduzida', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('MANUTENCAO', 'Manutenção'), ('INDISPONIVEL', 'Indisponível')], default='DISPONIVEL', max_length=20)),
                ('visibilidade', models.CharField(choices=[('PUBLICO_GERAL', 'Público geral'), ('COMUNIDADE_ACADEMICA', 'Comunidade académica')], default='COMUNIDADE_ACADEMICA', max_length=30)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
                'permissions': [('aprovar_reserva', 'Aprovar reservas'), ('gerir_recursos', 'Gerir recursos (salas e viaturas)'), ('ver_auditoria_espacos', 'Ver auditoria de espaços'), ('admin_unidade_espacos', 'Administrar unidade (espaços)')],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('cor_r', models.PositiveSmallIntegerField(default=0)),
                ('cor_g', models.PositiveSmallIntegerField(default=0)),
                ('cor_b', models.PositiveSmallIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'unidade',
                'verbose_name_plural': 'unidades',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PedidoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modulo', models.CharField(choices=[('SALA', 'Salas'), ('VIATURA', 'Viaturas')], max_length=10)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('numero_pessoas', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('observacao_admin', models.TextField(blank=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_reserva_criados', to=settings.AUTH_USER_MODEL)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_reserva', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido de reserva',
                'verbose_name_plural': 'pedidos de reserva',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='espacos.pedidoreserva')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='espacos.sala')),
            ],
            options={
                'verbose_name': 'ocorrência de reserva',
                'verbose_name_plural': 'ocorrências de reserva',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=80)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('utilizador_acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historicos_reserva_acoes', to=settings.AUTH_USER_MODEL)),
                ('ocorrencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos', to='espacos.ocorrenciareserva')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='espacos.pedidoreserva')),
            ],
            options={
                'verbose_name': 'histórico de reserva',
                'verbose_name_plural': 'históricos de reserva',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='sala',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salas', to='espacos.unidade'),
        ),
        migrations.CreateModel(
            name='AuditoriaEspacos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(blank=True, choices=[('SALA', 'Salas'), ('VIATURA', 'Viaturas')], max_length=10, null=True)),
                ('acao', models.CharField(max_length=80)),
                ('entidade', models.CharField(max_length=80)),
                ('entidade_id', models.CharField(blank=True, max_length=64)),
                ('descricao', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_espacos', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='espacos.unidade')),
            ],
            options={
                'verbose_name': 'auditoria (espaços)',
                'verbose_name_plural': 'auditorias (espaços)',
                'ordering': ['-criado_em'],
                'permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=20)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('cor', models.CharField(blank=True, max_length=40)),
                ('capacidade', models.PositiveIntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='espacos/viaturas/')),
                ('descricao', models.TextField(blank=True, default='')),
                ('localizacao', models.CharField(max_length=255)),
                ('recursos', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('MANUTENCAO', 'Manutenção'), ('INDISPONIVEL', 'Indisponível')], default='DISPONIVEL', max_length=20)),
                ('visibilidade', models.CharField(choices=[('PUBLICO_GERAL', 'Público geral'), ('COMUNIDADE_ACADEMICA', 'Comunidade académica')], default='COMUNIDADE_ACADEMICA', max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viaturas', to='espacos.unidade')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('unidade', 'matricula')},
            },
        ),
        migrations.AddField(
            model_name='ocorrenciareserva',
            name='viatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='espacos.viatura'),
        ),
        migrations.CreateModel(
            name='TokenReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('acao', models.CharField(choices=[('APROVAR', 'Aprovar'), ('REJEITAR', 'Rejeitar')], max_length=10)),
                ('usado', models.BooleanField(default=False)),
                ('expira_em', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='espacos.pedidoreserva')),
            ],
            options={
                'indexes': [models.Index(fields=['pedido', 'acao', 'usado'], name='espacos_tok_pedido__068429_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerfilUnidadeEspacos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_salas', models.BooleanField(default=True)),
                ('admin_viaturas', models.BooleanField(default=False)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis_unidade_espacos', to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis_admin', to='espacos.unidade')),
            ],
            options={
                'verbose_name': 'perfil de unidade (espaços)',
                'verbose_name_plural': 'perfis de unidade (espaços)',
                'unique_together': {('utilizador', 'unidade')},
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('modulo', models.CharField(choices=[('SALA', 'Salas'), ('VIATURA', 'Viaturas')], max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizacoes', to='espacos.unidade')),
            ],
            options={
                'verbose_name': 'localização',
                'verbose_name_plural': 'localizações',
                'ordering': ['nome'],
                'unique_together': {('unidade', 'nome', 'modulo')},
            },
        ),
        migrations.AddIndex(
            model_name='ocorrenciareserva',
            index=models.Index(fields=['sala', 'data_inicio', 'data_fim'], name='espacos_oco_sala_id_6376bc_idx'),
        ),
        migrations.AddIndex(
            model_name='ocorrenciareserva',
            index=models.Index(fields=['viatura', 'data_inicio', 'data_fim'], name='espacos_oco_viatura_f48863_idx'),
        ),
        migrations.AddIndex(
            model_name='ocorrenciareserva',
            index=models.Index(fields=['status', 'sala'], name='espacos_oco_status_be8a55_idx'),
        ),
        migrations.AddIndex(
            model_name='ocorrenciareserva',
            index=models.Index(fields=['status', 'viatura'], name='espacos_oco_status_b118e9_idx'),
        ),
    ]
