# Generated by Django 5.1.15 on 2026-06-03 14:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('SUBMETIDA', 'Submetida'), ('EM_ANALISE', 'Em análise'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('INCUBADA', 'Incubada')], default='SUBMETIDA', max_length=20)),
                ('submetida_em', models.DateTimeField(auto_now_add=True)),
                ('nome_startup', models.CharField(max_length=255)),
                ('email_contacto', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'candidatura',
                'verbose_name_plural': 'candidaturas',
                'ordering': ['-submetida_em'],
            },
        ),
        migrations.CreateModel(
            name='Edicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ano', models.PositiveIntegerField(unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'edição',
                'verbose_name_plural': 'edições',
                'ordering': ['-ano'],
            },
        ),
        migrations.CreateModel(
            name='ClassificacaoCandidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pontuacao', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('classificacao', models.PositiveIntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('avaliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('candidatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classificacao', to='startups.candidatura')),
            ],
            options={
                'verbose_name': 'classificação',
                'verbose_name_plural': 'classificações',
            },
        ),
        migrations.CreateModel(
            name='FormularioCandidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('aberto_em', models.DateTimeField(blank=True, null=True)),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='startups.edicao')),
            ],
            options={
                'verbose_name': 'formulário de candidatura',
                'verbose_name_plural': 'formulários de candidatura',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='candidatura',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidaturas', to='startups.formulariocandidatura'),
        ),
        migrations.CreateModel(
            name='CampoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('TEXT', 'Texto'), ('EMAIL', 'Email'), ('NUMBER', 'Número'), ('CHOICE', 'Escolha'), ('TEXTAREA', 'Texto longo')], max_length=20)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('opcoes', models.JSONField(blank=True, default=list, help_text='Lista de opções para campos do tipo CHOICE.')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='startups.formulariocandidatura')),
            ],
            options={
                'verbose_name': 'campo do formulário',
                'verbose_name_plural': 'campos do formulário',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('estado_residencia', models.CharField(choices=[('CANDIDATA', 'Candidata'), ('INCUBADA', 'Incubada'), ('SAIDA', 'Saída')], default='CANDIDATA', max_length=20)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('telefone_contacto', models.CharField(blank=True, max_length=30)),
                ('edicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='startups', to='startups.edicao')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startups', to='empresas.empresa')),
            ],
            options={
                'ordering': ['nome'],
                'permissions': [('gerir_formularios_candidatura', 'Gerir formulários de candidatura'), ('ver_candidaturas', 'Ver candidaturas'), ('alterar_estado_candidatura', 'Alterar estado da candidatura'), ('classificar_candidatura', 'Classificar candidatura')],
            },
        ),
        migrations.CreateModel(
            name='ContratoResidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='startups.startup')),
            ],
            options={
                'verbose_name': 'contrato de residência',
                'verbose_name_plural': 'contratos de residência',
                'ordering': ['-data_fim'],
            },
        ),
        migrations.AddField(
            model_name='candidatura',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidaturas', to='startups.startup'),
        ),
        migrations.CreateModel(
            name='RespostaCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField()),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='startups.campoformulario')),
                ('candidatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='startups.candidatura')),
            ],
            options={
                'verbose_name': 'resposta',
                'verbose_name_plural': 'respostas',
                'unique_together': {('candidatura', 'campo')},
            },
        ),
    ]
