# Generated by Django 5.1.15 on 2026-06-23 12:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEventoSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('cor', models.CharField(default='#3B82F6', max_length=7)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo de evento de segurança',
                'verbose_name_plural': 'tipos de evento de segurança',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='AvisoSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('nivel', models.CharField(choices=[('INFO', 'Informação'), ('ALERTA', 'Alerta'), ('CRITICO', 'Crítico')], default='INFO', max_length=20)),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos_seguranca_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'aviso de segurança',
                'verbose_name_plural': 'avisos de segurança',
                'ordering': ['-data_inicio', '-created_at'],
                'permissions': [('view_avisoseguranca', 'Ver avisos de segurança'), ('gerir_avisos', 'Gerir avisos de segurança'), ('gerir_ocorrencias', 'Gerir ocorrências de segurança'), ('gerir_eventos', 'Gerir eventos de segurança')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OcorrenciaSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('data_hora', models.DateTimeField()),
                ('local', models.CharField(blank=True, default='', max_length=255)),
                ('estado', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_TRATAMENTO', 'Em tratamento'), ('FECHADA', 'Fechada')], default='ABERTA', max_length=20)),
                ('observacoes_resolucao', models.TextField(blank=True, default='')),
                ('registado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_seguranca_registadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ocorrência de segurança',
                'verbose_name_plural': 'ocorrências de segurança',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='EventoSeguranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('descricao', models.TextField(blank=True, default='')),
                ('local', models.CharField(blank=True, default='', max_length=255)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_seguranca_criados', to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='avisos_seguranca.tipoeventoseguranca')),
            ],
            options={
                'verbose_name': 'evento de segurança',
                'verbose_name_plural': 'eventos de segurança',
                'ordering': ['data_inicio'],
            },
        ),
    ]
