# Generated by Django 5.1.15 on 2026-06-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avisos_seguranca', '0003_tipoocorrencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('cor', models.CharField(default='#6B7280', max_length=7)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'estado de ocorrência',
                'verbose_name_plural': 'estados de ocorrência',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='ocorrenciaseguranca',
            name='estado',
            field=models.CharField(default='ABERTA', max_length=40),
        ),
    ]
