# Generated by Django 5.1.15 on 2026-06-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_configuracaosistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='marketing_dry_run',
            field=models.BooleanField(blank=True, help_text='Vazio = usar variável de ambiente MARKETING_DRY_RUN.', null=True),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='marketing_linkedin_client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='marketing_linkedin_client_secret',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='marketing_linkedin_redirect_uri',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='marketing_media_public_base_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='marketing_meta_app_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='marketing_meta_app_secret',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuracaosistema',
            name='marketing_meta_redirect_uri',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
