# Generated by Django 5.1.15 on 2026-06-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(blank=True, default='', max_length=80)),
                ('modelo', models.CharField(blank=True, default='', max_length=80)),
                ('cor', models.CharField(blank=True, default='', max_length=40)),
                ('ano', models.PositiveIntegerField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='viaturas/')),
                ('descricao', models.TextField(blank=True, default='')),
                ('observacoes', models.TextField(blank=True, default='')),
                ('estado', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('MANUTENCAO', 'Em manutenção')], default='ATIVO', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'viatura',
                'verbose_name_plural': 'viaturas',
                'ordering': ['matricula'],
                'permissions': [],
            },
        ),
    ]
