# Generated by Django 5.1.15 on 2026-06-03 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('WORKSHOP', 'Workshop'), ('DEMO_DAY', 'Demo Day'), ('COMPETICAO', 'Competição'), ('OUTRO', 'Outro')], max_length=20)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('descricao', models.TextField(blank=True)),
                ('edicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='startups.edicao')),
            ],
            options={
                'ordering': ['data_inicio'],
                'permissions': [('view_dashboard', 'Ver dashboard'), ('gerir_eventos', 'Gerir eventos')],
            },
        ),
    ]
