# Generated by Django 5.1.15 on 2026-06-12 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_tipoevento_configuravel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MembroEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='dashboard.evento')),
                ('utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros_evento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membro de evento',
                'verbose_name_plural': 'membros de evento',
                'unique_together': {('evento', 'email')},
            },
        ),
    ]
