# Generated by Django 5.1.15 on 2026-06-19 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_evento_particular_criado_por'),
        ('empresas', '0004_tipointeracao_tarefa_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='empresas.empresa'),
        ),
    ]
