# Generated by Django 5.1.15 on 2026-06-03 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('TEXTO_LIVRE', 'Texto livre'), ('EVENTO', 'Evento'), ('OUTRO', 'Outro')], default='TEXTO_LIVRE', max_length=20)),
                ('data', models.DateField()),
                ('conteudo', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('registado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_registados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'entrada de histórico',
                'verbose_name_plural': 'entradas de histórico',
                'ordering': ['-data', '-created_at'],
            },
        ),
    ]
