# Generated by Django 5.1.15 on 2026-06-19 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notificacao'),
        ('dashboard', '0006_evento_particular_criado_por'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificacao',
            new_name='core_notifi_utiliza_a9d477_idx',
            old_name='core_notifi_utiliza_idx',
        ),
        migrations.AddField(
            model_name='historicoentrada',
            name='evento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacao_empresa', to='dashboard.evento'),
        ),
    ]
