# Generated by Django 5.1.15 on 2026-06-03 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('resumo', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('ATIVO', 'Ativo'), ('PAUSADO', 'Pausado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=20)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'secção',
                'verbose_name_plural': 'secções',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PROGRESSO', 'Em progresso'), ('CONCLUIDO', 'Concluído'), ('BLOQUEADO', 'Bloqueado')], default='PENDENTE', max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivos_responsavel', to=settings.AUTH_USER_MODEL)),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='projetos.secao')),
            ],
            options={
                'verbose_name': 'objetivo',
                'verbose_name_plural': 'objetivos',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
