# Generated by Django 5.1.15 on 2026-06-25 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0010_objetivo_urgente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='campopersonalizado',
            name='tipo',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('NUMERO', 'Número'), ('DATA', 'Data')], max_length=10),
        ),
        migrations.CreateModel(
            name='AnexoObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ficheiro', models.FileField(upload_to='projetos/objetivos/%Y/%m/')),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho', models.PositiveIntegerField()),
                ('tipo_mime', models.CharField(blank=True, max_length=100)),
                ('carregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_objetivo', to=settings.AUTH_USER_MODEL)),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='projetos.objetivo')),
            ],
            options={
                'verbose_name': 'anexo de tarefa',
                'verbose_name_plural': 'anexos de tarefa',
                'ordering': ['created_at'],
            },
        ),
    ]
