/** Rótulos para filtro de auditoria (valor interno = código `acao`, texto = português). */
const ROTULOS_ACAO: Record<string, string> = {
  CRIACAO_USUARIO: "Novo utilizador (auto-registo)",
  LOGIN_USUARIO: "Login efetuado",
  LOGOUT_USUARIO: "Logout",
  PEDIDO_REDEFINICAO_SENHA: "Pedido de redefinição de senha",
  REDEFINICAO_SENHA: "Senha redefinida",
  REATIVOU_LOCALIZACAO: "Localização reativada",
  CRIOU_LOCALIZACAO: "Localização criada",
  CRIOU_SALA: "Sala criada",
  EDITOU_SALA: "Sala editada",
  DESATIVOU_SALA: "Sala desativada",
  DESATIVOU_LOCALIZACAO: "Localização desativada",
  CRIOU_RESERVA: "Reserva criada",
  EDITOU_RESERVA: "Reserva editada",
  CANCELOU_RESERVA: "Reserva cancelada",
  CRIOU_UNIDADE: "Unidade criada",
  ALTEROU_UNIDADE: "Unidade alterada",
  CRIOU_USUARIO: "Utilizador criado",
  ALTEROU_TIPO_USUARIO: "Perfil de utilizador alterado",
  EXCLUIU_USUARIO: "Utilizador excluído",
  VINCULOU_ADMIN_UNIDADE: "Administrador associado à unidade",
  DESVINCULOU_ADMIN_UNIDADE: "Administrador desassociado da unidade",
  SUBSTITUIU_LOGO_SITE: "Logo do site substituído",
  ALTEROU_MODULOS_SITE: "Módulos do site alterados",
  ADMIN_CRIOU_RESERVA: "Reserva criada (admin)",
  ADMIN_EDITOU_RESERVA: "Reserva editada (admin)",
  APROVOU_RESERVA: "Reserva aprovada",
  REJEITOU_RESERVA: "Reserva rejeitada",
  ADMIN_CANCELOU_RESERVA: "Reserva cancelada (admin)",
  CRIOU_VIATURA: "Viatura criada",
  EDITOU_VIATURA: "Viatura editada",
  DESATIVOU_VIATURA: "Viatura desativada",
  CRIOU_LOCALIZACAO_VIATURA: "Localização de viatura criada",
  REATIVOU_LOCALIZACAO_VIATURA: "Localização de viatura reativada",
  DESATIVOU_LOCALIZACAO_VIATURA: "Localização de viatura desativada",
  CRIOU_RESERVA_VIATURA: "Reserva de viatura criada",
  EDITOU_RESERVA_VIATURA: "Reserva de viatura editada",
  CANCELOU_RESERVA_VIATURA: "Reserva de viatura cancelada",
  ADMIN_CRIOU_RESERVA_VIATURA: "Reserva de viatura criada (admin)",
  ADMIN_EDITOU_RESERVA_VIATURA: "Reserva de viatura editada (admin)",
  APROVOU_RESERVA_VIATURA: "Reserva de viatura aprovada",
  REJEITOU_RESERVA_VIATURA: "Reserva de viatura rejeitada",
  ADMIN_CANCELOU_RESERVA_VIATURA: "Reserva de viatura cancelada (admin)",
  // Legado (antes da migração)
  SUPER_CRIOU_UNIDADE: "Unidade criada",
  SUPER_ALTEROU_UNIDADE: "Unidade alterada",
  SUPER_CRIOU_USUARIO: "Utilizador criado",
  SUPER_ALTEROU_TIPO_USUARIO: "Perfil de utilizador alterado",
  SUPER_EXCLUIU_USUARIO: "Utilizador excluído",
  SUPER_VINCULOU_ADMIN_UNIDADE: "Administrador associado à unidade",
  SUPER_DESVINCULOU_ADMIN_UNIDADE: "Administrador desassociado da unidade"
};

export function rotuloAcaoAuditoria(acao: string): string {
  return ROTULOS_ACAO[acao] ?? acao;
}
